[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "alacritty"]

[window]
opacity = 0.80

[colors.primary]
background = "0x000000"

[font]
size = 12.0
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
