install-kitty-config: uninstall-kitty-config
	@echo "[-] installing kitty configuration"
	@mkdir -p ~/.config/kitty/
	@cp ./kitty/config/* ~/.config/kitty/
	@echo "[*] installing kitty configuration completed"

uninstall-kitty-config:
	@echo "[-] uninstalling kitty configuration"
	@rm -rf ~/.config/kitty/
	@echo "[*] uninstalling kitty configuration completed"

