shell:
 program: fish

window:
  opacity: 0.80

font:
  normal:
    family: DroidSansM Nerd Font Mono
    style: Regular
  bold:
    family: DroidSansM Nerd Font Mono
    style: Bold
  italic:
    family: DroidSansM Nerd Font Mono
    style: Italic
  bold_italic:
    family: DroidSansM Nerd Font Mono
    style: Bold Italic
  size: 12
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
 
colors:
  primary:
    background: '0x000000'
  normal:
    black: "#202020"
    green: "#98c379"
    yellow: "#d19a66"
    blue: "#61afef"
    red: "#CC0000"
    white: "#D3D7CF"
    magenta: "#c678dd"
    cyan: "#56b6c2"
  bright:
    black: "#88807C"
    red: "#F15D22"
    green: "#73C48F"
    yellow: "#FFCE51"
    blue: "#48B9C7"
    magenta: "#AD7FA8"
    cyan: "#34E2E2"
    white: "#EEEEEC"
 
