install-gtk-config:
	@echo "[-] installing gtk configuration"
	@mkdir -p ~/.config/gtk-3.0/
	@cp -r ./gtk/config/* ~/.config/gtk-3.0/
	@echo "[*] installing gtk configuration completed"

uninstall-gtk-config:
	@echo "[-] uninstalling gtk configuration"
	@rm -f ~/.config/gtk-3.0/settings.ini
	@echo "[*] uninstalling gtk configuration completed"
