install-scripts:
	@echo "[-] installing scripts"
	@mkdir -p ~/.local/bin/
	@cp ./scripts/config/tts ~/.local/bin/tts
	@echo "[*] installing scripts completed"

uninstall-scripts:
	@echo "[-] uninstalling scripts"
	@rm -f ~/.local/bin/tts
	@echo "[*] uninstalling scripts completed"
